#!/bin/bash

DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )

rm $HOME/.zshrc
ln -s $DIR/.zshrc $HOME/.zshrc

rm $HOME/.gitconfig
ln -s $DIR/.gitconfig $HOME/.gitconfig

rm $HOME/.vimrc
ln -s $DIR/.vimrc $HOME/.vimrc

