#!/usr/bin/env bash
# Work in progress
# Install tmuxinator
gem install tmuxinator
mkdir ~/.bin
curl https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.bash >> ~/.bin/tmuxinator.bash 
