#!/usr/bin/env bash
# Work in progress

# Install pathogen.vim
mkdir -p ~/.vim/autoload ~/.vim/bundle && \
curl -LSso ~/.vim/autoload/pathogen.vim https://tpo.pe/pathogen.vim

# Install tmuxinator
gem install tmuxinator
mkdir ~/.bin
curl https://raw.githubusercontent.com/tmuxinator/tmuxinator/master/completion/tmuxinator.bash >> ~/.bin/tmuxinator.bash 
